services:
  - type: web
    name: flowbridge-api-primary
    env: python
    region: oregon
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "cd backend && python app.py"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: INSTANCE_ID
        value: render-primary
      - key: MONGO_URI
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: JWT_SECRET_KEY
        sync: false
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: R2_ACCOUNT_ID
        sync: false
      - key: R2_ACCESS_KEY_ID
        sync: false
      - key: R2_SECRET_ACCESS_KEY
        sync: false
      - key: R2_BUCKET_FILES
        value: flowbridge-files
      - key: R2_BUCKET_THUMBS
        value: flowbridge-thumbs
      - key: R2_BUCKET_ZIPS
        value: flowbridge-zips
      - key: B2_ENDPOINT_URL
        sync: false
      - key: B2_ACCESS_KEY_ID
        sync: false
      - key: B2_SECRET_ACCESS_KEY
        sync: false
      - key: B2_BUCKET_FILES
        value: flowbridge-files-replica
      - key: B2_BUCKET_THUMBS
        value: flowbridge-thumbs-replica
      - key: B2_BUCKET_ZIPS
        value: flowbridge-zips-replica
      - key: UPSTASH_REDIS_REST_URL
        sync: false
      - key: UPSTASH_REDIS_REST_TOKEN
        sync: false
    healthCheckPath: /health
    autoDeploy: true
